kirill-konshin/next-redux-wrapper

src/index.js

When you pass a component without props it shows the following error:
`TypeError: Cannot convert undefined or null to object
at Function.keys (<anonymous>)
at WrappedCmp (/Users/DLYA/Desktop/DLYA/BDevelopers/bd-admin-front/node_modules/next-redux-wrapper/src/index.js:56:20)
at /Users/DLYA/Desktop/DLYA/BDevelopers/bd-admin-front/node_modules/react-dom/lib/ReactCompositeComponent.js:306:16
at measureLifeCyclePerf (/Users/DLYA/Desktop/DLYA/BDevelopers/bd-admin-front/node_modules/react-dom/lib/ReactCompositeComponent.js:75:12)
at ReactCompositeComponentWrapper._constructComponentWithoutOwner (/Users/DLYA/Desktop/DLYA/BDevelopers/bd-admin-front/node_modules/react-dom/lib/ReactCompositeComponent.js:305:14)
at ReactCompositeComponentWrapper._constructComponent …

fix for component without props

---

src/index.js

Another proposal, this change should be in line with recent changes to `initStore`.
The package already provides the next.js page context `req` and `isServer` properties to `makeStore`, this change also makes the `query` object available too. When using next.js API `.render(req, res, page, query)` method to render a page one could provide initial store data via the `query` object

Add next page context `query` object to initStore

---

README.md
package.json
src/__snapshots__/index.server.spec.js.snap
src/__snapshots__/index.spec.js.snap
src/index.js
src/index.server.spec.js
src/index.spec.js

This PR should add tests to bring coverage close to 100%. It tests the various new configuration options and also the differences or memoization or not on the client vs server.
I have also made a small fix/tweak to the logic around setting the `debug` flag as discovered when writing the tests

Add tests and documentation updates

---

package-lock.json
package.json
src/index.js

`Object.assign` is used with out polyfilling. Projects that are using `next-redux-wrapper` will not transpile it with babel, because babel ignores `node_modules` directory.

Add Object.assign polyfill

---

README.md
src/index.js
src/index.server.spec.js
src/index.spec.js

This PR implements two additional options called `serializeState` and `deserializeState`. The idea is to allow users to implement a custom logic how to serialize the redux state on the server and how to deserialize it on the client.
This comes handy if the user wants to store instances of complex types in the state, using techniques like EJSON (https://github.com/primus/ejson).
Todos:

Allow users to implement custom logic for serializing and deserializing the redux state.

---

README.md
src/index.js
src/index.spec.js

(This PR implements #83 for the upcoming 2.x version.)
This PR implements two additional options called `serializeState` and `deserializeState`. The idea is to allow users to implement a custom logic how to serialize the redux state on the server and how to deserialize it on the client.
This comes handy if the user wants to store instances of complex types in the state, using techniques like EJSON (https://github.com/primus/ejson).

2.x: Allow users to implement custom logic for serializing and deserializing the redux state.

---

packages/wrapper/src/index.tsx

Hi. Thank you for your awesome library.
I am greatly helped by this library for using next + redux + typescript.
Now I write `getInitialProps` with `NextJSContext` and use `store`'s state value.
But type of store is `any` because it dosen't know type of state and actions.
So, I add generics to `NextJSContext` based on `Store` of `redux`.
It is not breaking change because these generics have default type.
https://github.com/reduxjs/redux/blob/master/index.d.ts#L160-L168
Thanks.

Add generics to NextJSContext

---

.huskyrc
lerna.json
packages/configs/package.json
packages/demo/.babelrc
packages/demo/jest-puppeteer.config.js
packages/demo/next-env.d.ts
packages/demo/next.config.js
packages/demo/package.json
packages/demo/tests/index.test.ts
packages/demo/tsconfig.json
packages/wrapper/package.json
packages/wrapper/src/index.spec.tsx
packages/wrapper/src/index.tsx

Using nextjs9 with the current version just break the typings experience. This is just a initial commit to up the version. @kirill-konshin please feel free to edit the PR to move forwards with nextjs 9 typings. This could break those that are still in less than nextjs 9.0.

Nextjs 9 Typescript changes

---

README.md

Per the deprecation warning about `Container` [here](https://github.com/zeit/next.js/blob/canary/errors/app-container-deprecated.md) for Next v9.04,removing this from the README example.
If you'd rather keep the README as is and just have a "NOTE" about this deprecation for the versions, let me know and can adjust accordingly.

Update README to remove deprecated Container from next/app dependency

---

README.md

The Usage section doesn't exist in the doc and there is no Installation nav item. So the Usage item has been replaced with Installation in the nav.

Rename Usage item in nav menu to Installation in README.md

---

README.md

* Add motivation section (#170)
* Add TypeScript examples (#176, #177)
* Make installation code blocks expandable
* Migrate connected Page components to functional components
* Group tips and examples in a Tips and Tricks section
* Some grammar & style improvements
* Remove outdated typings reference in Resources section
* Add npm package badge
* Remove deprecated Container notice
I didn't find time to walk through the Tips and Tricks section yet – I think it could profit from TS examples as well.

Revise Readme (fixes #170)

---

README.md

This PR adds reudx hooks usage documentation, providing an example for its usage.
Also "fixes" #163 .

Add Redux Hooks usage documentation

---

README.md

Found some un-imported and unused interfaces in the README TypeScript example

Fix imports in README.md TypeScript example

---

README.md

In README.md, type generic is present at the javascript example.

Fix: readme.md typo

---

README.md

I was reading the README yesterday and I noticed that some examples import the `Provider` but it is not needed anymore (at least the docs say so).
I don't know if it was intended, but I think it might confuse people if it stays there. That's why I'am removing the references.

Remove unused Provider imports from README examples

---

packages/wrapper/src/index.tsx

Hi @kirill-konshin ,
I requested PR a couple of days ago. because of compatibility problem with Next.js v9.5.5+
Thank you for merge. 
But announced Next.js v10 yesterday.
So need a few more types for resolve the compatibility problem.
What if there is a reason to use custom types instead of import types?
I'm having a compatibility problem.
Thank you for the quick merge and I'd like to request a quick release.

Modify custom type to imported type from next

---

README.md

Type annotations can only be used in TypeScript files.

Remove type annotations from code snippet

---

README.md
packages/wrapper/src/index.tsx
packages/wrapper/tests/client.spec.tsx
packages/wrapper/tests/server.spec.tsx
packages/wrapper/tests/testlib.tsx

Fix hot reloading issues by removing the store from window

---

README.md
packages/demo-redux-toolkit/store.tsx

Per the `createSlice` documentation, `extraReducers` can also be "a mapping from action types to action-type-specific case reducer functions". That removes the need for
```ts
const hydrate = createAction<AppState>(HYDRATE);
```
like in the `builder.addCase()` approach.
This PR also removes the (circular) slice.name reference in the HYDRATE reducer as it breaks type inference for the slice. A tiny bit of redundancy is better than untyped slices, I guess.

Simplify slice creation in redux-toolkit demo

---

README.md

Hi @kirill-konshin, it's me again tinkering with the readme :smile:
I've been maintaining a little library called [next-redux-cookie-wrapper](https://github.com/bjoluc/next-redux-cookie-wrapper) for a while now that started as a drop-in replacement to next-redux-wrapper, configuring next-redux-wrapper to use Redux Persist and redux-persist-cookie-storage for improved SSR. Recently, I rewrote the whole thing to support next-redux-wrapper v6 and v7 and get rid of Redux Persist. Instead of a drop-in replacement, it is now an extension to next-redux-wrapper that ships as a Redux middleware.
I figured this might be of interest for a broader audience now, so this PR adds a few references to the readme where applicable. I hope they are neither to bold, nor to many. Thanks in advance for …

Reference next-redux-cookie-wrapper in the readme

---

packages/wrapper/src/index.tsx
packages/wrapper/tests/server.spec.tsx

PR fixes issue described in https://github.com/kirill-konshin/next-redux-wrapper/issues/325

Fix wrapper.getInitialAppProps() incompatible with Next's AppInitialProps

---

README.md

Even though you've mentioned in the issue tracker that you should not use the `window.__NEXT_REDUX_WRAPPER_STORE__` my product was doing some hacky solutions with it and I would not be surprised that this information would benefit others.
Might be good to add this to the release notes as well.
We rely heavily on this fantastic project, thank you so much.

Mention __NEXT_REDUX_WRAPPER_STORE__ being removed in migration notes.

---

README.md

I saw that there were some minor code missing from the documentation for redux toolkit typescript users. I'm not sure about the compatibility - here's my relevant package.json:
```
"@reduxjs/toolkit": "^1.9.2",
"next": "^13.1.5",
"next-redux-wrapper": "^8.1.0",
```
I modified the documentation so it better matched these redux toolkit docs - [Correct typings for the Dispatch type](https://redux-toolkit.js.org/usage/usage-with-typescript#correct-typings-for-the-dispatch-type). Not sure if this is totally necessary but I figure it may help people who are starting a new project like I am.

Added convenience methods for redux-toolkit typescript users
